/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.ifsul.bcc.lpoo.om.gui.cliente;

import br.edu.ifsul.bcc.lpoo.om.Controle;
import java.awt.CardLayout;

/**
 *
 * @author Carol
 */
public class JPanelCliente extends javax.swing.JPanel {

    /**
     * Creates new form JPanelCliente
     */
    
    private JPanelClienteListagem listagem;
    private Controle controle;
    
    public JPanelCliente(Controle controle) {
        this.controle = controle;
        listagem = new JPanelClienteListagem(this, controle);
        initComponents();
        
        this.add(listagem, "tela_cliente_listagem");
        
        showTela("tela_cliente_listagem");
    }
    
    public void showTela(String nomeTela){
        
        if(nomeTela.equals("tela_cliente_listagem")){
            
          //  listagem.populaTable();
            
        }
        
       ((CardLayout) this.getLayout()).show(this, nomeTela);
        
    }
    
    public Controle getControle() {
        return controle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
